# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
