# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_auto_20171020_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='parties',
            field=models.ManyToManyField(related_name='agreements', to='agreements.Country'),
        ),
    ]
